export { validateStudyBundle } from './validate.js';
export type { ValidationIssue, ValidationResult } from './validate.js';
export { buildGenerationPrompt } from './prompt.js';
export { generateStudyBundle } from './generate.js';
export type { LLMClient, GenerateResult } from './generate.js';
export { createGeminiClient, DEFAULT_GEMINI_MODEL } from './providers/gemini.js';
export type { GeminiClientOptions } from './providers/gemini.js';
export { attachMedia } from './media.js';
export type { SpeechClient, ImageClient, MediaClients, AttachMediaResult } from './media.js';
export { createGeminiSpeechClient, DEFAULT_SPEECH_MODEL, DEFAULT_VOICE } from './providers/gemini-speech.js';
export type { GeminiSpeechOptions } from './providers/gemini-speech.js';
export { prepareGenerateRequest, GenerationRequestError, MAX_SOURCE_CHARS } from './request.js';
export { STUDY_BUNDLE_JSON_SCHEMA } from './schema.js';
